security:
    # Configuration des gestionnaires de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définition du fournisseur d'utilisateurs (provider)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        # Route de développement (ne s'applique pas à l'administration)
        dev:
            pattern: ^/admin
            security: true

        # Configurer le firewall principal
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthAuthenticator
            logout:
                path: app_logout
                # Redirection après déconnexion
                target: app_home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Contrôle d'accès pour les utilisateurs
    access_control:
        # Accès réservé aux utilisateurs avec le rôle ADMIN pour /admin et ses sous-routes
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Accès aux pages profil seulement pour les utilisateurs authentifiés
        - { path: ^/profile, roles: ROLE_USER }
        # Accès aux utilisateurs connectés (ROLE_USER ou plus) pour devenir administrateur
        - { path: ^/admin/devenir-admin, roles: ROLE_USER }
