<?php

namespace ContainerFHap02s;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PFQj3gaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pFQj3ga' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pFQj3ga'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loansRepository' => ['privates', 'App\\Repository\\LoansRepository', 'getLoansRepositoryService', true],
        ], [
            'loansRepository' => 'App\\Repository\\LoansRepository',
        ]);
    }
}
