<?php

namespace Container5A7Ynd3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5uYReCxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5uYReCx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5uYReCx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookLoanRepo' => ['privates', 'App\\Repository\\BookLoanRepository', 'getBookLoanRepositoryService', true],
        ], [
            'bookLoanRepo' => 'App\\Repository\\BookLoanRepository',
        ]);
    }
}
